name: bosh-release
on:
  pull_request:
  workflow_dispatch:  
jobs:
  manifest:
    name: Manifest Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: false

      - name: Install Dependencies
        run: |
          set -euxo pipefail

          export BOSH_VERSION=6.4.4
          wget -q https://github.com/cloudfoundry/bosh-cli/releases/download/v${BOSH_VERSION}/bosh-cli-${BOSH_VERSION}-linux-amd64 && \
          mv bosh-cli-* /usr/local/bin/bosh && \
          chmod +x /usr/local/bin/bosh

          export CUE_VERSION=0.4.0
          wget -q -O - https://github.com/cue-lang/cue/releases/download/v${CUE_VERSION}/cue_v${CUE_VERSION}_linux_amd64.tar.gz \
          | tar xfz - cue
          mv cue /usr/local/bin/

      - name: Run Tests
        run: |
          set -euxo pipefail

          make -C example/operation/tests test
